const PROJECTS = [
  {
    slug: "surrealistic-collage-art",
    title: "Surrealistic Collage Art",
    cover: "/image/cover-Surrealistic.jpg",
    images: [
      "/project-images/Surrealistic-1.jpg",
      "/project-images/Surrealistic-2.jpg",
      "/project-images/Surrealistic-3.jpg",
      "/project-images/Surrealistic-4.jpg",
      "/project-images/Surrealistic-5.jpg",
      "/project-images/Surrealistic-6.jpg",
      "/project-images/Surrealistic-7.jpg",
      "/project-images/Surrealistic-8.jpg",
      "/project-images/Surrealistic-9.jpg",
      "/project-images/Surrealistic-10.jpg",
      "/project-images/Surrealistic-11.jpg",
      "/project-images/Surrealistic-12.jpg",
      "/project-images/Surrealistic-13.jpg",
      "/project-images/Surrealistic-14.jpg",
      "/project-images/Surrealistic-15.jpg",
      "/project-images/Surrealistic-16.jpg",
      "/project-images/Surrealistic-17.jpg",
      "/project-images/Surrealistic-18.jpg",
      "/project-images/Surrealistic-19.jpg",
      "/project-images/Surrealistic-20.jpg",
      "/project-images/Surrealistic-21.jpg",
      "/project-images/Surrealistic-22.jpg",
      "/project-images/Surrealistic-23.jpg",
      "/project-images/Surrealistic-24.jpg",
      "/project-images/Surrealistic-25.jpg",
      "/project-images/Surrealistic-26.jpg",
      "/project-images/Surrealistic-27.jpg",
      "/project-images/Surrealistic-28.jpg",
      "/project-images/Surrealistic-29.jpg",
      "/project-images/Surrealistic-30.jpg",
      "/project-images/Surrealistic-31.jpg",
      "/project-images/Surrealistic-32.jpg",
      "/project-images/Surrealistic-33.jpg",
      "/project-images/Surrealistic-34.jpg",
      "/project-images/Surrealistic-35.jpg",
      "/project-images/Surrealistic-36.jpg",
    ],
    description: "Embark on a journey of surreal creativity! From 2020 to 2023, I curated an enchanting collection of surreal collages for ITONICS' Blog channel, exploring innovation management, foresight, and strategy. These captivating visuals not only enhanced the channel's appeal but also became intrinsic to the company's identity. With remarkable engagement rates, they have evolved beyond their initial role, sought after by both external clients and internal stakeholders for various platforms and initiatives. Discover how these timeless creations continue to influence narratives and ignite imaginations today.",
  },
  {
    slug: "insurance-trend-report",
    title: "Insurance Trend Report",
    cover: "/image/cover-Insurance.png",
    images: [
      "/project-images/Insurance-1.jpg",
      "/project-images/Insurance-2.jpg",
      "/project-images/Insurance-3.jpg",
      "/project-images/Insurance-4.jpg",
      "/project-images/Insurance-5.jpg",
      "/project-images/Insurance-6.jpg",
      "/project-images/Insurance-7.jpg",
      "/project-images/Insurance-8.jpg",
      "/project-images/Insurance-9.jpg",
      "/project-images/Insurance-10.jpg",
      "/project-images/Insurance-11.jpg",
      "/project-images/Insurance-12.jpg",
    ],
    description: `The inaugural B2C insurance report marks the beginning of a compelling Trend report series by ITONICS. It explores contemporary trends and future scenarios to uncover innovation opportunities across industries. 

    Designed for digital platforms, it utilizes a graphic style featuring human and urban-themed photographs, consistent with the company's brand colors. Each spread is carefully crafted to integrate photography and content seamlessly, delivering a cohesive message. This report is housed within ITONICS' digital resource center, serving as a valuable asset for enhancing innovation skills.
    `,
  },
  {
    slug: "sustainability-trend-report",
    title: "Sustainability Trend Report",
    cover: "/image/cover-Sustainability.png",
    images: [
      "/project-images/Sustainability-1.jpg",
      "/project-images/Sustainability-2.jpg",
      "/project-images/Sustainability-3.jpg",
      "/project-images/Sustainability-4.jpg",
      "/project-images/Sustainability-5.jpg",
      "/project-images/Sustainability-6.jpg",
      "/project-images/Sustainability-7.jpg",
      "/project-images/Sustainability-8.jpg",
      "/project-images/Sustainability-9.jpg",
      "/project-images/Sustainability-10.jpg",
      "/project-images/Sustainability-11.jpg",
    ],
    description: "January 2020 marked the start of the Decade of Action, a pivotal time for environmentalists, aligned with the UN 2030 Agenda for Sustainable Development. This report, the second installment of the Trend report series by ITONICS, underscores the urgency of innovative solutions amid climate change. Carefully curated images in this report center on activism and critique of the man-made climate crisis, maintaining aesthetic appeal. Informative infographics and clear text hierarchies prioritize key information.",
  },
  {
    slug: "social-media",
    title: "Social Media",
    cover: "/image/cover-Social-Media.jpg",
    images: [
      "/project-images/Social-1.png",
      "/project-images/Social-2.png",
      "/project-images/Social-3.png",
      "/project-images/Social-4.png",
      "/project-images/Social-5.png",
      "/project-images/Social-6.png",
      "/project-images/Social-7.png",
      "/project-images/Social-8.jpg",
      "/project-images/Social-9.jpg",
      "/project-images/Social-10.jpg",
      "/project-images/Social-11.jpg",
      "/project-images/Social-12.png",
      "/project-images/Social-13.png",
      "/project-images/Social-14.png",
    ],
    description: `My time within marketing teams has been a masterclass in the pivotal role social channels play for any company. Crafting content for these platforms isn't just about aesthetics—it's about stepping into the shoes of the audience we aim to captivate. I've discovered that the same visual style doesn't always resonate across all companies and contexts. Here, I proudly present a diverse collection of social media pieces, each meticulously tailored to engage and inspire varied audiences.`,
  },
  {
    slug: "design-posters",
    title: "Design Posters",
    cover: "/image/cover-Posters.png",
    images: [
      "/project-images/Posters-1.jpg",
      "/project-images/Posters-2.jpg",
    ],
    description: `This internal project was a thrilling opportunity to explore alternative ways of communicating the benefits of ITONICS Foresight product. Tasked with creating posters showcasing the advantages of various ITONICS products, I seized the chance to highlight the trend anticipation, emerging opportunity identification, and effective risk management features of the Foresight product. Taking a storytelling approach, I aimed to develop something original and extraordinary. The resulting posters were offered as free downloadable material for office decoration or unrestricted use.`,
  },
  {
    slug: "set-of-illustrations-for-itonics",
    title: "Set of Illustrations for ITONICS",
    cover: "/image/cover-Illustrations.png",
    images: [
      "/project-images/Illustrations-1.png",
      "/project-images/Illustrations-2.gif",
      "/project-images/Illustrations-3.png",
      "/project-images/Illustrations-4.png",
      "/project-images/Illustrations-5.png",
      "/project-images/Illustrations-6.png",
      "/project-images/Illustrations-7.png",
    ],
    description: `These illustrations serve as visual representations of ITONICS' array of software products. Combining software screenshots with vectorial shapes, they exude a dynamic and attention-grabbing aesthetic. Positioned as the hero section on each product page of the website, they provided an engaging introduction to each software offering.`,
  },
  {
    slug: "presentation-brochure-design",
    title: "Presentation Brochure Design",
    cover: "/image/cover-Brochure.jpg",
    images: [
      "/project-images/Brochure-1.jpg",
      "/project-images/Brochure-2.jpg",
      "/project-images/Brochure-3.jpg",
      "/project-images/Brochure-4.jpg",
      "/project-images/Brochure-5.jpg",
      "/project-images/Brochure-6.jpg",
      "/project-images/Brochure-7.jpg",
      "/project-images/Brochure-8.jpg",
      "/project-images/Brochure-9.jpg",
      "/project-images/Brochure-10.jpg",
      "/project-images/Brochure-11.jpg",
      "/project-images/Brochure-12.jpg",
      "/project-images/Brochure-13.jpg",
      "/project-images/Brochure-14.jpg",
      "/project-images/Brochure-15.jpg",
      "/project-images/Brochure-16.jpg",
      "/project-images/Brochure-17.jpg",
      "/project-images/Brochure-18.jpg",
      "/project-images/Brochure-19.jpg",
      "/project-images/Brochure-20.jpg",
    ],
  },
  {
    slug: "catalogue-design",
    title: "Catalogue Design",
    cover: "/image/cover-Catalogue.png",
    images: [
      "/project-images/Catalogue-1.jpg",
      "/project-images/Catalogue-2.jpg",
      "/project-images/Catalogue-3.jpg",
      "/project-images/Catalogue-4.jpg",
    ],
  },
  {
    slug: "9th-design-price-mario-hernandez",
    title: "9th Design Price MARIO HERNANDEZ",
    cover: "/image/cover-Premio.png",
    images: [
      "/project-images/Premio-1.png",
      "/project-images/Premio-2.jpg",
      "/project-images/Premio-3.jpg",
      "/project-images/Premio-4.jpg",
      "/project-images/Premio-5.jpg",
    ],
  },
  {
    slug: "traveling-guide-viajes-con-estilo",
    title: "Traveling guide Viajes con estilo",
    cover: "/image/cover-Traveling.png",
    images: [
      "/project-images/Traveling-1.jpg",
      "/project-images/Traveling-2.jpg",
      "/project-images/Traveling-3.jpg",
      "/project-images/Traveling-4.jpg",
      "/project-images/Traveling-5.jpg",
      "/project-images/Traveling-6.jpg",
    ],
  },
  {
    slug: "turistic-guide-of-the-center-in-bogota",
    title: "Turistic guide of the center in Bogota",
    cover: "/image/cover-Guia.jpg",
    images: [
      "/project-images/Guia-1.jpg",
      "/project-images/Guia-2.jpg",
      "/project-images/Guia-3.jpg",
      "/project-images/Guia-4.jpg",
      "/project-images/Guia-5.jpg",
      "/project-images/Guia-6.jpg",
    ],
  },
];
  
export default PROJECTS;